# Generated by Django 4.1.1 on 2023-01-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GastApp', '0003_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
